### ISSUE TITLE
Hooks not called

### ISSUE THREAD

**Issue by igore13** [theumod/uMod.Hurtworld#63]
Hi,
I tested with Puts(string) :
- object OnClanCreate(Clan clan)   => **Hook Not Called**
- object OnClanDisband(Clan clan)   => Hook Called
- object OnClanMemberAdd(Clan clan, PlayerSession session, PlayerSession session2)   => **Hook Not Called**
- void OnClanCreated(Clan clan)   => **Hook Not Called**
- void OnClanDisbanded(Clan clan)   => Hook Called
- void OnClanMemberAdded(Clan clan, PlayerSession session, PlayerSession session2)   => Hook Called

Thanks

**Comment by lukespragg** [comment]
Should be fixed in the upcoming build, just missed some changes in the release that were in develop. Th

**Comment by pim-moeskops** [comment]
Hello,

You are using **OnClanCreate** with the wrong arguments, we changed them to:
```cs
void OnClanCreate(string clanName, string clanTag, Color color, string description, PlayerSession session)
```
Using it as an object works as well but there are some problems with the ui getting locked.

**OnClanMemberAdd** seems to work fine, so i'm not sure what problem you are having with that.


**OnClanCreated** is should be fixed in the latest build.
